### ISSUE TITLE
app-config.yaml update should not necessitate having to rebuild/redeploy

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/book#5]
## Goal
This epic aims to provide a mechanism to update the app-config.yaml without having to rebuild or redeploy the Backstage application. Although this may be available today, it's not well-known or documented. Let's go ahead and provide an opinionated approach as to how to approach this, which is well documented and that we can demo from the Janus Showcase App.

## Acceptance Criteria
- [x] As a platform engineer, I want to be able to update a software template and make it available through the Backstage portal without having to rebuild or redeploy the Backstage application.
- [x] As a platform engineer, I want to be able to create a new software template and make it available through the Backstage portal without having to rebuild or redeploy the Backstage application.

**Comment by rtaniwa** [comment]
@christophe-f i think we can consider this one in progress now given we have verified the approach in the showcase app?

**Comment by christophe-f** [comment]
@rtaniwa yes we can even close this issue as the implementation is complete.

**Comment by christophe-f** [comment]
In the `app-config.yaml`, we need to point a new location with to remote url such as the one in showcase

```
catalog:
  locations:
    - type: url
      target: https://github.com/janus-idp/software-templates/blob/main/showcase-templates.yaml
      rules:
        - allow: [Template]
```

This is a one time setup. Then we only have to update the `targets` section in the [remote yaml](https://github.com/janus-idp/software-templates/blob/main/showcase-templates.yaml) file. Backstage will update the list of templates within minutes without any deployments or restarts.
